// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agdtvgjkmssshkitrlhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZHR2Z2prbXNzc2hraXRybGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjUyNTMsImV4cCI6MjA1OTUwMTI1M30.OUTZmhCswOxlqiqtTspm1kfubNdt9OyHXwWsJL10_Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);